version: "3"
services:
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - ${USER_PORT}:${USER_PORT}
    restart: always
    volumes:
      - .:/app
      - /app/user/node_modules
    env_file:
      - ./dev.env
      - ./.env
  theater:
    build:
      dockerfile: Dockerfile
      context: ./theater
    container_name: theater
    ports:
      - ${THEATER_PORT}:${THEATER_PORT}
    restart: always
    volumes:
      - .:/app
      - /app/theater/node_modules
    env_file:
      - ./dev.env
      - ./.env

  socket:
    build:
      dockerfile: Dockerfile
      context: ./socket
    container_name: socket
    ports:
      - ${SOCKET_PORT}:${SOCKET_PORT}
    restart: always
    volumes:
      - .:/app
      - /app/socket/node_modules
    env_file:
      - ./dev.env
      - ./.env

  poll:
    build:
      dockerfile: Dockerfile
      context: ./poll
    container_name: poll
    ports:
      - ${POLL_PORT}:${POLL_PORT}
    restart: always
    volumes:
      - .:/app
      - /app/poll/node_modules
    env_file:
      - ./dev.env
      - ./.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    container_name: proxy
    environment:
      - USER_PORT=${USER_PORT}
      - THEATER_PORT=${THEATER_PORT}
      - SOCKET_PORT=${SOCKET_PORT}
      - POLL_PORT=${POLL_PORT}
    depends_on:
      - user
      - theater
      - socket
      - poll
    ports:
      - "80:80"
